services:
  api:
    # image: ghcr.io/abdelrahmany25/todo_cqrs/api:latest
    build: .
    container_name: backend
    ports:
    - "8080:8080"
    networks:
      - app-net
    restart: unless-stopped
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TodoCQRS;User Id=sa;Password=${MSSQL_SA_PASSWORD};Integrated Security=True;Trust Server Certificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    restart: unless-stopped
    networks:
      - app-net
    ports:
      - "1433:1433"
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - sqlserver-data:/var/opt/mssql

networks:
  app-net:
    driver: bridge

volumes:
  sqlserver-data: