name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p ~/Todo_CQRS
            cd ~/Todo_CQRS
            git pull origin main
            echo "MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}" > .env
            docker compose pull
            docker compose up -d